### ISSUE TITLE
error unpacking payload: 'PingMessage' object has no attribute 'payload_field_names'

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/ping-python#55]
When running the example, I'm getting the same error as this guy:
https://discuss.bluerobotics.com/t/python-to-access-the-ping-raw-data-on-raspberry-pi/4225/7
```
 ✘ patrick@pichau  /tmp  ~/.local/bin/simplePingExample.py --device /dev/ttyUSB0
Opening /dev/ttyUSB0 at 115200 bps
error unpacking payload: 'PingMessage' object has no attribute 'payload_field_names'
msg_data: bytearray(b'BBBR\x02\x00\xb2\x04\x00\x00\xc3\x12!\x02'), header: (66, 66, 21058, 2, 178, 4)
Traceback (most recent call last):
  File "/home/patrick/.local/lib/python3.7/site-packages/brping/pingmessage.py", line 497, in unpack_msg_data
    payload = struct.unpack(PingMessage.endianess + self.get_payload_format(), self.msg_data[PingMessage.headerLength:PingMessage.headerLength + self.payload_length])                                                                                                                                            
  File "/home/patrick/.local/lib/python3.7/site-packages/brping/pingmessage.py", line 540, in get_payload_format
    var_length = self.get_payload_length() - payload_dict[self.message_id]["payload_length"]  # Subtract static length portion from payload length
  File "/home/patrick/.local/lib/python3.7/site-packages/brping/pingmessage.py", line 531, in get_payload_length
    return payload_dict[self.message_id]["payload_length"] + len(getattr(self, self.payload_field_names[-1]))
AttributeError: 'PingMessage' object has no attribute 'payload_field_names'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patrick/.local/bin/simplePingExample.py", line 20, in <module>
    if myPing.initialize() is False:
  File "/home/patrick/.local/lib/python3.7/site-packages/brping/ping1d.py", line 95, in initialize
    if self.request(pingmessage.PING1D_VOLTAGE_5) is None:
  File "/home/patrick/.local/lib/python3.7/site-packages/brping/ping1d.py", line 114, in request
    return self.wait_message(m_id, timeout)
  File "/home/patrick/.local/lib/python3.7/site-packages/brping/ping1d.py", line 126, in wait_message
    msg = self.read()
  File "/home/patrick/.local/lib/python3.7/site-packages/brping/ping1d.py", line 76, in read
    if self.parser.parse_byte(ord(b)) == pingmessage.PingParser.NEW_MESSAGE:
  File "/home/patrick/.local/lib/python3.7/site-packages/brping/pingmessage.py", line 664, in parse_byte
    self.rx_msg = PingMessage(msg_data=self.buf)
  File "/home/patrick/.local/lib/python3.7/site-packages/brping/pingmessage.py", line 445, in __init__
    self.unpack_msg_data(msg_data)
  File "/home/patrick/.local/lib/python3.7/site-packages/brping/pingmessage.py", line 501, in unpack_msg_data
    print("format: %s, buf: %s" % (PingMessage.endianess + self.get_payload_format(), self.msg_data[PingMessage.headerLength:PingMessage.headerLength + self.payload_length]))                                                                                                                                    
  File "/home/patrick/.local/lib/python3.7/site-packages/brping/pingmessage.py", line 540, in get_payload_format
    var_length = self.get_payload_length() - payload_dict[self.message_id]["payload_length"]  # Subtract static length portion from payload length
  File "/home/patrick/.local/lib/python3.7/site-packages/brping/pingmessage.py", line 531, in get_payload_length
    return payload_dict[self.message_id]["payload_length"] + len(getattr(self, self.payload_field_names[-1]))
AttributeError: 'PingMessage' object has no attribute 'payload_field_names'
```

**Comment by jaxxzer** [comment]
I'm having no problem here. Are you using python 3?
```sh
[jacob@jacob-laptop ~]$ pip freeze | grep bluerobotics-ping
bluerobotics-ping==0.0.6
[jacob@jacob-laptop ~]$ simplePingExample.py --device /dev/ttyUSB0 --baudrate 9600
Opening /dev/ttyUSB0 at 9600 bps
------------------------------------
Starting Ping..
Press CTRL+C to exit
------------------------------------
Press Enter to continue...
Distance: 1480	Confidence: 59%
Distance: 1480	Confidence: 59%
Distance: 1493	Confidence: 47%
Distance: 1530	Confidence: 49%
Distance: 1530	Confidence: 49%
Distance: 1618	Confidence: 63%
Distance: 1656	Confidence: 63%
```

**Comment by jaxxzer** [comment]
I'm having no problem with python2 or python3

**Comment by jaxxzer** [comment]
```

**Comment by jaxxzer** [comment]
The problem is with corrupt data making it through the parser:
in @patrickelectric output:

> msg_data: bytearray(b'BBBR\x02\x00\xb2\x04\x00\x00\xc3\x12!\x02'), header: (66, 66, 21058, 2, 178, 4)
