### ISSUE TITLE
Error Ping on simulation

### ISSUE THREAD

**Issue by senceryazici** [bluerobotics/ping-python#58]
python tools/ping1d-simulation.py

```
Traceback (most recent call last):
  File "tools/ping1d-simulation.py", line 162, in <module>
    sim.sendMessage(PING1D_PROFILE)
  File "tools/ping1d-simulation.py", line 76, in sendMessage
    msg.pack_msg_data()
  File "/Users/senceryazici/Local Documents/auv/ping-python/brping/pingmessage.py", line 487, in pack_msg_data
    self.msg_data = bytearray(struct.pack(msg_format, *values))
struct.error: argument for 's' must be a string
```

**Comment by patrickelectric** [comment]
Which version of Python are you using ?
Only Python is supported.

**Comment by senceryazici** [comment]
Your answer got me thinking and I realized that the python version problem occurred because another installation messed up the PATH variable, so I was using the wrong python. Thanks.
